[package]
name = "fuzzel-rbw"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "frbw"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.219", features = [ "derive"] }
serde_json = "1.0.141"

